# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

#Magento shop admin email
shop_admin_email: <your-email-here>

# Guest OS timezone
timezone: Europe/Zagreb

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: shop

# Virtual machine IP
ip: 192.168.83.152

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
